apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-local-storage
  local:
    path: /var/es-disk01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: work
          operator: In
          values:
          - infra
