apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    app: elasticsearch
spec:
  storageClassName: es-local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
